### ISSUE TITLE
If you haven't join any survey you get a list with all the surveys in the system

### ISSUE THREAD

**Issue by rgamez** [cobweb-eu/pcapi#25]
If you access /pcapi/surveys/local/<uuid> and you haven't join any survey (for example a new user coming from gmail) you will get all the surveys available in the system

**Comment by xmichael** [comment]
PCAPI has no control of the survey associations. This is a portal bug.

**Comment by Delawen** [comment]
Are you trying with an old user? Users created more than one month ago (before the final private survey workflow was defined) may have this issue. If you experience this with an old user, just send me the uuid and I will fix it.

**Comment by rgamez** [comment]
In addition to my user I tested a gmail user that I used before in the portal, but you are right I try with a new user and I don't have the problem, I guess we can close this one. thanks.
