### ISSUE TITLE
Use HTML5 canvas to generate thumbnails

### ISSUE THREAD

**Issue by xmichael** [cobweb-eu/pcapi#33]
Currently FTOpen depends on PCAPI to generate image thumbnails. This functionality is better suited to FTOpen itself using HTML5/canvas.

**Comment by gmh04** [comment]
Currently the pcapi does the following when an image is posted:

1) create smaller image at 480px width
2) create thumbnail
3) rename the orginal file with '_orig'

From what I understand about the cobweb viewer it doesn't use 1.  And the app doesn't use any.  So we can simply remove all resizing on the pcapi and instead post two files - the original image and a thumbnail created by the client.

Creating a thumbnail using HTML5 Canvas toDataURL will return a base64 string.  To ajax POST the string to the pcapi will require a change to the pcapi to decode the string.  I would suggest adding a URL parameter (e.g isbase64=true) as opposed to attempting to determine whether the body is a base64 string or binary (or in fact simply the content of a text file).
