### ISSUE TITLE
refactor /records/ filter functionality to use the new pcapi.provider.Records module

### ISSUE THREAD

**Issue by xmichael** [cobweb-eu/pcapi#40]
Refactor [rest.py#193](https://github.com/cobweb-eu/pcapi/blob/master/src/pcapi/rest.py#L193) to use the newer pcapi.provider.Records module while removing reduntant code from rest.py like filter_data().

As an example the new module is already used for the WFS GetFeature functionality [here](https://github.com/cobweb-eu/pcapi/blob/master/src/pcapi/ows/WFS.py#L128)

NOTE : This is a very challenging task because code in rest.py has accumulated too many ad-hoc bug-fixes over the years.

**Comment by xmichael** [comment]
Addendum: the new modules under pcapi.provider should use dictionaries rather than bottle HTTPRequest GET/POST parameters. There is a helper function that will convert the HTTPRequest to a dictionary of lower-case parameters at [helper.py#22](https://github.com/cobweb-eu/pcapi/blob/master/src/pcapi/helper.py#L22) which is what the OWS implementation uses.

**Comment by gmh04** [comment]
checked with @panterz and agreed that filter "media" is no longer used in Survey Designer
