### ISSUE TITLE
Attribute within range (pillar 2)

### ISSUE THREAD

**Issue by xmichael** [cobweb-eu/pcapi#46]
**An implementation of "attribute within range" method as part of the PCAPI filter chain using the same architecture and syntax as the PiP filter.**

Example syntax:
`filter=rangecheck&rangecheck_name=height&rangecheck_min=1&rangecheck_max=2`

Clarifications:
 * `rangechange_name`, `rangecheck_min` and `rangecheck_max` are all cast to floats. If casting fails the returned value is `{ error:1, msg: "Cannot convert X to float" }`
 * Any parameter can be omitted but not both
 * filters should be tested to be chainable without any extra development effort. For example the pip and rangecheck (or any other pcapi filter) should be chain-able with this syntax:

`filter=pip,rangecheck&pip_point=[1,1]&pip_polygon=[[0,0],[0,2],[2,2],[2,0]],rangecheck_name=height&rangecheck_min=1&rangecheck_max=2`

which should only return values within the specified polygon and range

**Comment by gmh04** [comment]
@xmichael  couple of clarifications.

If `rangecheck_min` or `rangecheck_max` parameter is omitted, do you want the omitted value to be the same as the defined value, so it would be a test for equality?  Alternatively you could make `rangecheck_max` mandatory and give rangecheck_min a default value of 0.

Does `rangechange_name` match the id of a property field? i.e:

```
{
  "type": "Feature",
  "geometry": {
    "type": "Point",
    "coordinates": [
      -2.236263725924374,
      53.43324078909734
    ]
  },
  "properties": {
    "editor": "a42049ec-89b8-431d-a2e2-e0fd50739a77.json",
    "fields": [
      {
        "id": "text-1",  <<==================
        "type": "text",
        "val": "test",
        "label": "Group name"
      },
      ...
```

**Comment by xmichael** [comment]
The `rangecheck_name` should be the `id` of the field

We should probably avoid any complicated solutions regarding parametres. If `rangecheck_min` is omitted then we just check that `value < rangecheck_max` -- any value below that would pass the filter including negative floats. Similarly for when `rangecheck_max` is omitted.
